version: '3.8'

services:
  app:
    build:
      context: ./Eleicao
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - ./Eleicao:/var/www
    working_dir: /var/www
    networks:
      - laravel
    depends_on:
      - postgres

  web:
    image: nginx:alpine
    container_name: nginx_web
    ports:
      - "8000:80"
    volumes:
      - ./Eleicao:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: laravel
      POSTGRES_PASSWORD: laravel
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
    driver: bridge
